### PR TITLE
fix: comment has encoded

### LINKED ISSUE #230: HTML comment tags are encoded
1. Run XSS via the following params: `filterXSS('<!-- foo -->', {allowCommentTag: true})`

Expected output: `<!-- foo -->`
Actual output: `&lt;!-- foo --&gt;`

Version: `xss@1.0.8`

### PR DESCRIPTION
**Pull request by lumburr**
close #230

### CODE REVIEW

File: lib/default.js [hunk 1]
```diff
@@ -344,10 +355,12 @@ function onIgnoreTagStripAll() {
  */
 function StripTagBody(tags, next) {
   if (typeof next !== "function") {
-    next = function () {};
+    next = function () {
+    };
   }
```
Comment (leizongmin) [inline lib/default.js:360]: 这里的修改与本次要修复的问题无关

Comment (lumburr) [reply lib/default.js]: done
